apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: systemadmintest
  namespace: argocd  # เปลี่ยน namespace ของ Argo CD เป็น argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PekoyamaPeko02/SystemAdminTest02.git'
    targetRevision: HEAD
    path: systemadmintest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: systemadmintest  # เปลี่ยน namespace ให้ตรงกับแอปพลิเคชัน
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
