apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-content
data:
  nginx-content.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }

