apiVersion: v1
kind: Namespace
metadata:
  name: systemadmintest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemadmintest
  namespace: systemadmintest
  labels:
    app: systemadmintest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: systemadmintest
  template:
    metadata:
      labels:
        app: systemadmintest
    spec:
      containers:
      - name: crud-container
        image: systemadmintest:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: systemadmintest-service
  namespace: systemadmintest
spec:
  selector:
    app: systemadmintest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30127
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: systemadmintest-ingress
  namespace: systemadmintest
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: "nginx"  # Use ingress class explicitly
  rules:
    - host: systemadmintest.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: systemadmintest-service
                port:
                  number: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: systemadmintest
  namespace: argocd  # เปลี่ยน namespace ของ Argo CD เป็น argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PekoyamaPeko02/SystemAdminTest02.git'
    targetRevision: HEAD
    path: systemadmintest/systemadmintest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: systemadmintest  # เปลี่ยน namespace ให้ตรงกับแอปพลิเคชัน
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
