apiVersion: v1
kind: Namespace
metadata:
  name: systemadmintest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemadmintest
  namespace: systemadmintest
  labels:
    app: systemadmintest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: systemadmintest
  template:
    metadata:
      labels:
        app: systemadmintest
    spec:
      containers:
      - name: crud-container
        image: node:14-alpine
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: crud-source
          mountPath: /app
        command: ["npm", "start"]
      volumes:
      - name: crud-source
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: systemadmintest-service
  namespace: systemadmintest
spec:
  selector:
    app: systemadmintest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: systemadmintest-ingress
  namespace: systemadmintest
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: "nginx"  # Use ingress class explicitly
  rules:
    - host: systemadmintest.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: systemadmintest-svc
                port:
                  number: 80

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: systemadmintest
  namespace: systemadmintest
spec:
  project: default
  source:
    repoURL: 'https://github.com/PekoyamaPeko02/SystemAdminTest02.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true



