apiVersion: v1
kind: Namespace
metadata:
  name: systemadmintest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemadmintest-deploy
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemadmintest
  template:
    metadata:
      labels:
        app: systemadmintest
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: nginx-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-content
          configMap:
            name: my-nginx-content

---
apiVersion: v1
kind: Service
metadata:
  name: systemadmintest-svc
  namespace: argocd
  labels:
    app: systemadmintest
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: systemadmintest
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: systemadmintest-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx" # ปรับปรุงให้ใช้ ingressClassName แทน
spec:
  ingressClassName: "nginx" # เพิ่มการตั้งค่านี้
  rules:
    - host: systemadmintest.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: systemadmintest-svc
                port:
                  number: 80
