apiVersion: v1
kind: Namespace
metadata:
  name: systemadmintest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemadmintest-deploy
  namespace: systemadmintest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemadmintest
  template:
    metadata:
      labels:
        app: systemadmintest
    spec:
      containers:
      - name: systemadmintest
        image: <your_docker_image> # ใส่ URL ของ Docker Image ที่สร้างขึ้น
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: systemadmintest-svc
  namespace: systemadmintest
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30444
  selector:
    app: systemadmintest
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: systemadmintest-ingress
  namespace: systemadmintest
  annotations:
    kubernetes.io/ingress.class: "nginx"  # ปรับปรุงให้ใช้ ingressClassName แทน
spec:
  ingressClassName: "nginx"  # เพิ่มการตั้งค่านี้
  rules:
    - host: systemadmintest.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: systemadmintest-svc
                port:
                  number: 80
